<?php
    session_start();

    $config = \Suggestotron\Config::get('site');

?>
<!doctype html>
<html>
<head>
    <title><?=$config['title']; ?></title>

    <link href="/css/custom.css" rel="stylesheet" type="text/css" >

    <!--    Bootstrap ccss-->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-theme.min.css" rel="stylesheet">

    <!--    jQuery 2.1.0-->
    <script src="/js/jquery-2.1.0.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-xs-6 col-md-8">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="/">Suggestotron</a>
                    </div>
                </div>
                <div class="col-xs-6 col-md-4">
                    <form class="navbar-form navbar-right" role="search">
                        <a href="/topic/add" class="btn btn-default ">
                            <span class="glyphicon glyphicon-plus-sign"></span>
                            Add Topic
                        </a>
                    </form>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</nav>

<div class="container ">
    <?php
    // display success message
    if (isset($_SESSION['success']))
    {
        ?>
        <div>
            <div class="alert alert-success alert-dismissible text-center">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>
                    <?php
                    echo $_SESSION['success'];
                    unset($_SESSION['success']);
                    ?>
                </p>
            </div>
        </div>
        <?php
    }
    ?>
    <?php
    // display error message
    if (isset($_SESSION['error']))
    {
        ?>
        <div>
            <div class="alert alert-danger alert-dismissible text-center">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>
                    <?php
                    echo $_SESSION['error'];
                    unset($_SESSION['error']);
                    ?>
                </p>
            </div>
        </div>
        <?php
    }

    ?>
<!--    Specific page content goes here-->
    <?php $this->content(); ?>
    <hr>
</div>
<footer class="footer nav navbar">
    <div class="container text-center">
        <span class="text-muted">All right reserved, Kelechi WebDesign &copy <?= date("Y") ?></span>
    </div>
</footer>
<!--JavaScript Code-->
<script type="text/javascript">
    function showMessage() {
    // Get the snackbar DIV
    var x = document.getElementById("displayMessages");

    // Add the "show" class to DIV
    x.className = "show";

    // After 5 seconds, remove the show class from DIV
    setTimeout(function(){ x.className = x.className.replace("show", ""); }, 5000);
}
    $(document).ready(function(){
    $('[data-toggle="popover"]').popover();   
});
</script>

<!--Bootstrap 3.3.7-->
<script src="/js/bootstrap.min.js"></script>
</body>
</html>