<?php
$config = \Suggestotron\Config::get('site');
?>
<!doctype html>
<html>
<head>
    <title><?=$config['title']; ?></title>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/custom.css">
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/jquery-2.1.0.min.js"></script>

</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-10">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">Suggestotron</a>
                </div>
            </div>
            <div class="col-xs-2">
                <form navbar-form navbar-right role="search">
                    <a href="/topic/add" class="btn btn-default">
                        <span class="glyphicon glyphicon-plus-sign"></span>
                        Add Topic
                    </a>
                </form>
            </div>
        </div>
    </div>
</nav>

<div class="container">
<!--    Specific page content goes here-->
    <?php $this->content(); ?>
</div>
<footer class="footer">
    <div class="container">
        
    </div>
</footer>
<script type="text/javascript">
    $('[data-toggle="popover"]').popover();
</script>
</body>
</html>