<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <p>
                This is a PHPBrige tutorial on how to create a voting system on a particular topic.
                You are welcome to choose a topic and share with friends and see how they feel about it.
                <blockquote>
                     Exlusively developed on a step-by-step tutorial with lots of modifications.
                </blockquote>
                Do feel free to use the template for your own projects or contact me for further informations.

            </p>
        </div>
    </div>
	<a href="/topic/list">Back to list</a>
</div>