<?php

    $title = $_SESSION['title']? $_SESSION['title'] : false;
    $description = $_SESSION['description']? $_SESSION['description'] : false;
?>
<div class="container">

    <div class=" ">
        <h3>New Topic</h3>
        <form action="/topic/add" method="POST">
            <span class="rowMargin">
                <label class="labelLength" for="title" title="Title">
                    Title:
                </label>
                <input class="inputFont" id="title" type="text" name="title" size="41" value="<?= htmlentities($title); ?>">
            </span>
            <br>
            <span class="rowMargin">
                <label class="labelLength" for="description">
                    Description:
                </label>
                <textarea class="inputFont" id="description" name="description" cols="40" rows="10" ><?= htmlentities($description); ?></textarea>
            </span>
            <br>
            <label class="labelLength"></label>
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus-sign"></span>
                Add Topic
            </button>

        </form>
    </div>
</div>
