<div class="container">
    <div class=" ">
        <h2>New Topic</h2>
        <form action="/topic/add" method="POST">
            <span class="rowMargin">
                <label class="labelLength" for="title" title="Title">
                    Title:
                </label>
                <input class=inputFont id="title" type="text" name="title" size="41">
            </span>
            <br>
            <span class="rowMargin">
                <label class="labelLength" for="description">
                    Description:
                </label>
                <textarea class=inputFont id="description" name="description" cols="41" rows="10"></textarea>
            </span>
            <br>
            <label class="labelLength"></label><input type="submit" value="Add Topic" class="btn btn-primary">
        </form>
    </div>
</div>
